global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'event_receiver'
    metrics_path: /metrics
    static_configs:
      - targets: ['event_receiver:8000']

  - job_name: 'processing_worker'
    static_configs:
      - targets: ['processing_worker:8003']

  - job_name: 'persistence_worker'
    static_configs:
      - targets: ['persistence_worker:8004']

  - job_name: 'event_publisher'
    static_configs:
      - targets: ['event_publisher:8001']
      
